spring.application.name: ecm

upload:
  allowed-extensions: jpg,jpeg,png,webp,gif,bmp,tiff,svg,heic,heif,dng,raw,pdf,txt,doc,docx,xls,xlsx,ppt,pptx,zip,rar,7z,tar,gz,bz2,mp4,webm,avi,mkv,mov,wmv,flv,3gp,mpg,mpeg,ogv,mp3,wav,ogg,flac,aac,m4a,wma,opus,amr
  allowed-media-types: image/jpeg,image/png,image/webp,image/gif,image/bmp,image/svg+xml,image/heif,image/heic,image/x-adobe-dng,image/tiff,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/zip,application/vnd.rar,application/x-7z-compressed,application/x-tar,application/gzip,application/x-bzip2,video/mp4,video/webm,video/x-msvideo,video/x-matroska,video/quicktime,video/x-ms-wmv,video/x-flv,video/3gpp,video/mpeg,video/mpeg,video/ogg,audio/mpeg,audio/wav,audio/ogg,audio/flac,audio/aac,audio/mp4,audio/x-ms-wma,audio/opus,audio/amr
  path: ./uploads

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.flywaydb: DEBUG

server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 2000MB
    compress:
      enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 1KS5WhBcx6W0

  r2dbc:
    url: r2dbc:postgresql://103.71.96.96:5432/sba_dev
    username: admin
    password: dqBuBQJWwRGY
